"""Inspect the Windows native wheel and source-distribution boundaries."""

from __future__ import annotations

import argparse
import tarfile
import zipfile
from pathlib import Path, PurePosixPath


ANCHOR_FILENAMES = {
    "cuda_support_roadmap.md",
    "codebase_review_notes.md",
    "cuda_backend_selection.md",
    "windows_grammar_boundary.md",
    "d22_implementation_plan.md",
    "d23_implementation_plan.md",
}
LOCAL_REFERENCE_DIRECTORIES = {"local markdowns", "local_markdowns"}
GENERATED_PYTHON_SUFFIXES = {".pyc", ".pyo"}
NATIVE_BINARY_SUFFIXES = {".dll", ".dylib", ".pyd", ".so"}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wheel", required=True, type=Path)
    parser.add_argument("--sdist", required=True, type=Path)
    parser.add_argument("--forbidden-path", action="append", default=[])
    arguments = parser.parse_args()

    wheel_count = inspect_wheel(arguments.wheel, arguments.forbidden_path)
    sdist_count = inspect_sdist(arguments.sdist, arguments.forbidden_path)
    print(
        "native distribution inspection passed: "
        f"wheel_files={wheel_count} sdist_entries={sdist_count}"
    )


def inspect_wheel(path: Path, forbidden_paths: list[str]) -> int:
    with zipfile.ZipFile(path) as archive:
        names = archive.namelist()
        _require_clean_names(names, artifact="wheel")
        native_modules = [
            name
            for name in names
            if name.startswith("onyx_cuda/_grammar_native") and name.endswith(".pyd")
        ]
        if len(native_modules) != 1:
            raise AssertionError(
                f"wheel must contain exactly one namespaced native module, found {native_modules}"
            )
        all_native_binaries = [
            name for name in names if PurePosixPath(name).suffix.lower() in NATIVE_BINARY_SUFFIXES
        ]
        if all_native_binaries != native_modules:
            raise AssertionError(
                f"wheel contains an unexpected native binary: {all_native_binaries!r}"
            )
        if any(name.endswith((".rs", "Cargo.toml", "Cargo.lock")) for name in names):
            raise AssertionError("wheel contains Rust source or Cargo metadata")
        _require_forbidden_paths_absent(
            ((name, archive.read(name)) for name in names if not name.endswith("/")),
            forbidden_paths,
            artifact="wheel",
        )
    return len(names)


def inspect_sdist(path: Path, forbidden_paths: list[str]) -> int:
    with tarfile.open(path, "r:gz") as archive:
        members = [member for member in archive.getmembers() if member.isfile()]
        names = [member.name for member in members]
        _require_clean_names(names, artifact="sdist")
        if any(
            PurePosixPath(name).suffix.lower() in NATIVE_BINARY_SUFFIXES for name in names
        ):
            raise AssertionError("sdist contains a compiled native binary")
        if not names:
            raise AssertionError("sdist is empty")
        root = names[0].split("/", maxsplit=1)[0]
        expected_rust = {
            f"{root}/rust/Cargo.lock",
            f"{root}/rust/Cargo.toml",
            f"{root}/rust/src/json_parser.rs",
            f"{root}/rust/src/json_runtime.rs",
            f"{root}/rust/src/json_schema.rs",
            f"{root}/rust/src/lib.rs",
            f"{root}/rust/src/regex_runtime.rs",
        }
        actual_rust = {name for name in names if f"{root}/rust/" in name}
        if actual_rust != expected_rust:
            raise AssertionError(
                f"sdist native source boundary differs: actual={sorted(actual_rust)!r}"
            )
        _require_forbidden_paths_absent(
            ((member.name, archive.extractfile(member).read()) for member in members),
            forbidden_paths,
            artifact="sdist",
        )
    return len(names)


def _require_clean_names(names: list[str], *, artifact: str) -> None:
    for name in names:
        path = PurePosixPath(name)
        lowered_parts = {part.lower() for part in path.parts}
        suffix = path.suffix.lower()
        if "__pycache__" in lowered_parts or suffix in GENERATED_PYTHON_SUFFIXES:
            raise AssertionError(f"{artifact} contains generated bytecode/cache file {name!r}")
        if path.name in ANCHOR_FILENAMES:
            raise AssertionError(f"{artifact} contains ignored local anchor {path.name!r}")
        if path.name.startswith("d") and path.name.endswith("_implementation_plan.md"):
            raise AssertionError(f"{artifact} contains local implementation plan {path.name!r}")
        if lowered_parts & LOCAL_REFERENCE_DIRECTORIES:
            raise AssertionError(f"{artifact} contains local reference directory {name!r}")
        if any(part == "onyx" for part in path.parts):
            raise AssertionError(f"{artifact} contains the Mac package path {name!r}")


def _require_forbidden_paths_absent(
    entries,
    forbidden_paths: list[str],
    *,
    artifact: str,
) -> None:
    needles = {
        representation.encode()
        for path in forbidden_paths
        for representation in {path, path.replace("\\", "/"), path.replace("/", "\\")}
        if representation
    }
    for name, payload in entries:
        for needle in needles:
            if needle in payload:
                raise AssertionError(
                    f"{artifact} entry {name!r} contains forbidden local build path "
                    f"{needle.decode(errors='replace')!r}"
                )


if __name__ == "__main__":
    main()
