"""Public package identity for Onyx for Windows.

Importing this module is intentionally side-effect free: it does not probe hardware, initialize
CUDA, load a model, or import the macOS MLX engine.
"""

from .identity import ACCELERATOR_BACKEND, ENGINE_NAME, SUPPORTED_PLATFORM
from .backend import AutoregressiveBackend, BackendError, BackendStateError, ModelStep
from .cache import (
    CacheCheckpoint,
    CacheCheckpointStateError,
    CheckpointableAutoregressiveBackend,
)
from .draft import (
    DraftProposalCleanupError,
    DraftProposalError,
    DraftProposalInvariantError,
    DraftProposalResult,
    generate_draft_proposal,
)
from .acceptance import (
    MatchReplaceAcceptanceError,
    MatchReplaceAcceptanceInvariantError,
    MatchReplaceAcceptanceResult,
    decide_match_replace_acceptance,
)
from .speculative_iteration import (
    SpeculativeIterationCleanupError,
    SpeculativeIterationError,
    SpeculativeIterationInvariantError,
    SpeculativeIterationResult,
    coordinate_speculative_iteration,
)
from .verification import (
    BatchedTargetVerificationBackend,
    BatchedTargetVerificationResult,
)
from .hardware import (
    HardwareProbeError,
    NvidiaDevice,
    NvidiaSmiExecutionError,
    NvidiaSmiNotFoundError,
    NvidiaSmiOutputError,
    discover_nvidia_devices,
)
from .generation import (
    GenerationCleanupError,
    GenerationInvariantError,
    GenerationResult,
    generate_greedy,
    generate_target,
    select_highest_logit,
)
from .constrained_generation import (
    ConstrainedGenerationCleanupError,
    ConstrainedGenerationError,
    ConstrainedGenerationInvariantError,
    GrammarGenerationContext,
    GrammarLogitMask,
    GrammarNoContinuationError,
    GrammarSpecification,
    JsonSchemaGrammar,
    RegexGrammar,
    generate_constrained_target,
)
from .grammar import (
    GrammarCompilationError,
    GrammarCompiler,
    GrammarConstraint,
    GrammarError,
    GrammarRuntimeCompatibilityError,
    GrammarRuntimeUnavailableError,
    GrammarStateError,
    GrammarType,
)
from .metrics import (
    GrammarTimingMetrics,
    GrammarTimingSession,
    MetricsError,
    MetricsInvariantError,
    MetricsStateError,
    TargetGenerationMetrics,
    TargetMetricsSession,
    create_grammar_timing_session,
    create_target_metrics_session,
)
from .native_grammar import (
    NATIVE_GRAMMAR_ABI_VERSION,
    NATIVE_GRAMMAR_MODULE,
    NativeGrammarRuntimeInfo,
    load_native_grammar_runtime,
)
from .native_regex import NativeRegexConstraint, NativeRegexState, compile_native_regex
from .native_json import NativeJsonConstraint, NativeJsonState, compile_native_json_schema
from .selection import (
    GREEDY_SELECTION,
    MAX_SAMPLING_SEED,
    GreedySelection,
    SamplingDistributionError,
    SelectionError,
    SelectionPolicy,
    TemperatureTopPSelection,
    create_reference_sampler,
    validate_selection_policy,
)
from .tokenizer import TokenizerAdapter, TokenizerError, UnknownTextTokenError
from .text_engine import TargetTextEngine, VocabularyMismatchError
from .streaming import (
    StreamingCleanupError,
    StreamingError,
    StreamingInvariantError,
    TextGenerationComplete,
    TextGenerationDelta,
    TextGenerationEvent,
    TextGenerationResult,
)
from .torch_runtime import (
    TorchCudaError,
    TorchCudaImportError,
    TorchCudaProbeError,
    TorchCudaReadiness,
    TorchCudaUnavailableError,
    probe_torch_cuda,
)
from .model_profile import DEFAULT_TARGET_PROFILE, QWEN_3B_CANDIDATE_PROFILE, QwenModelProfile
from .production_tokenizer import (
    ProductionTokenizerError,
    ProductionTokenizerLoad,
    ProductionTokenizerLoadError,
    QwenTokenizerFingerprint,
    QwenTokenizerAdapter,
    TransformersImportError,
    build_qwen_grammar_vocabulary,
    load_qwen_tokenizer,
)
from .target_model import (
    QuantizedTargetCleanupError,
    QuantizedTargetError,
    QuantizedTargetImportError,
    QuantizedTargetLoadError,
    QuantizedTargetReadiness,
    QuantizedTargetUnavailableError,
    probe_quantized_target,
)
from .torch_backend import (
    TorchBackendError,
    TorchBackendExecutionError,
    TorchBackendImportError,
    TorchBackendInvariantError,
    TorchBackendLoadError,
    TorchCUDATargetBackend,
    load_torch_cuda_target,
    select_cuda_argmax,
)
from .torch_selection import create_cuda_sampler
from .torch_grammar_mask import (
    TorchCUDAGrammarLogitMask,
    TorchGrammarMaskError,
    TorchGrammarMaskExecutionError,
    TorchGrammarMaskImportError,
    TorchGrammarMaskInvariantError,
    TorchGrammarMaskUnavailableError,
    create_cuda_grammar_logit_mask,
)
from .torch_metrics import (
    TRANSFORMERS_DYNAMIC_CACHE_MODE,
    TorchMetricsError,
    TorchMetricsExecutionError,
    TorchMetricsImportError,
    TorchMetricsInvariantError,
    TorchMetricsUnavailableError,
    create_torch_metrics_session,
)
from .production_engine import (
    ProductionEngineCleanupError,
    ProductionEngineError,
    ProductionEngineLoadError,
    ProductionTargetTextStream,
    ProductionTargetTextEngine,
    load_production_target_engine,
)
from .candidate_qualification import (
    CandidateLifecycleMeasurement,
    CandidateMemorySnapshot,
    CandidateQualificationCleanupError,
    CandidateQualificationError,
    CandidateQualificationExecutionError,
    CandidateQualificationImportError,
    CandidateQualificationUnavailableError,
    CandidateTargetQualification,
    TokenizerCompatibilityReport,
    qualify_qwen_3b_candidate,
)

__all__ = [
    "ACCELERATOR_BACKEND",
    "AutoregressiveBackend",
    "BackendError",
    "BackendStateError",
    "BatchedTargetVerificationBackend",
    "BatchedTargetVerificationResult",
    "CacheCheckpoint",
    "CacheCheckpointStateError",
    "CandidateLifecycleMeasurement",
    "CandidateMemorySnapshot",
    "CandidateQualificationCleanupError",
    "CandidateQualificationError",
    "CandidateQualificationExecutionError",
    "CandidateQualificationImportError",
    "CandidateQualificationUnavailableError",
    "CandidateTargetQualification",
    "CheckpointableAutoregressiveBackend",
    "ConstrainedGenerationCleanupError",
    "ConstrainedGenerationError",
    "ConstrainedGenerationInvariantError",
    "DEFAULT_TARGET_PROFILE",
    "DraftProposalCleanupError",
    "DraftProposalError",
    "DraftProposalInvariantError",
    "DraftProposalResult",
    "ENGINE_NAME",
    "GenerationCleanupError",
    "GenerationInvariantError",
    "GenerationResult",
    "GREEDY_SELECTION",
    "GrammarCompilationError",
    "GrammarCompiler",
    "GrammarConstraint",
    "GrammarError",
    "GrammarGenerationContext",
    "GrammarLogitMask",
    "GrammarNoContinuationError",
    "GrammarSpecification",
    "GrammarRuntimeCompatibilityError",
    "GrammarRuntimeUnavailableError",
    "GrammarStateError",
    "GrammarTimingMetrics",
    "GrammarTimingSession",
    "GrammarType",
    "GreedySelection",
    "HardwareProbeError",
    "MetricsError",
    "MetricsInvariantError",
    "MetricsStateError",
    "NATIVE_GRAMMAR_ABI_VERSION",
    "NATIVE_GRAMMAR_MODULE",
    "NativeGrammarRuntimeInfo",
    "NativeJsonConstraint",
    "NativeJsonState",
    "NativeRegexConstraint",
    "NativeRegexState",
    "NvidiaDevice",
    "NvidiaSmiExecutionError",
    "NvidiaSmiNotFoundError",
    "NvidiaSmiOutputError",
    "ProductionTokenizerError",
    "ProductionTokenizerLoad",
    "ProductionTokenizerLoadError",
    "ProductionEngineCleanupError",
    "ProductionEngineError",
    "ProductionEngineLoadError",
    "ProductionTargetTextEngine",
    "ProductionTargetTextStream",
    "JsonSchemaGrammar",
    "MatchReplaceAcceptanceError",
    "MatchReplaceAcceptanceInvariantError",
    "MatchReplaceAcceptanceResult",
    "QWEN_3B_CANDIDATE_PROFILE",
    "QwenModelProfile",
    "QwenTokenizerAdapter",
    "QwenTokenizerFingerprint",
    "QuantizedTargetCleanupError",
    "QuantizedTargetError",
    "QuantizedTargetImportError",
    "QuantizedTargetLoadError",
    "QuantizedTargetReadiness",
    "QuantizedTargetUnavailableError",
    "RegexGrammar",
    "SUPPORTED_PLATFORM",
    "StreamingCleanupError",
    "StreamingError",
    "StreamingInvariantError",
    "TargetGenerationMetrics",
    "TargetMetricsSession",
    "TargetTextEngine",
    "TextGenerationComplete",
    "TextGenerationDelta",
    "TextGenerationEvent",
    "TextGenerationResult",
    "TorchCudaError",
    "TorchCudaImportError",
    "TorchCudaProbeError",
    "TorchCudaReadiness",
    "TorchCudaUnavailableError",
    "TorchBackendError",
    "TorchBackendExecutionError",
    "TorchBackendImportError",
    "TorchBackendInvariantError",
    "TorchBackendLoadError",
    "TorchCUDATargetBackend",
    "TorchCUDAGrammarLogitMask",
    "TorchGrammarMaskError",
    "TorchGrammarMaskExecutionError",
    "TorchGrammarMaskImportError",
    "TorchGrammarMaskInvariantError",
    "TorchGrammarMaskUnavailableError",
    "TorchMetricsError",
    "TorchMetricsExecutionError",
    "TorchMetricsImportError",
    "TorchMetricsInvariantError",
    "TorchMetricsUnavailableError",
    "TRANSFORMERS_DYNAMIC_CACHE_MODE",
    "TransformersImportError",
    "TokenizerAdapter",
    "TokenizerCompatibilityReport",
    "TokenizerError",
    "UnknownTextTokenError",
    "VocabularyMismatchError",
    "ModelStep",
    "MAX_SAMPLING_SEED",
    "SamplingDistributionError",
    "SelectionError",
    "SelectionPolicy",
    "SpeculativeIterationCleanupError",
    "SpeculativeIterationError",
    "SpeculativeIterationInvariantError",
    "SpeculativeIterationResult",
    "TemperatureTopPSelection",
    "create_cuda_sampler",
    "create_cuda_grammar_logit_mask",
    "create_grammar_timing_session",
    "create_reference_sampler",
    "create_target_metrics_session",
    "create_torch_metrics_session",
    "compile_native_regex",
    "compile_native_json_schema",
    "build_qwen_grammar_vocabulary",
    "coordinate_speculative_iteration",
    "decide_match_replace_acceptance",
    "discover_nvidia_devices",
    "generate_greedy",
    "generate_constrained_target",
    "generate_draft_proposal",
    "generate_target",
    "load_qwen_tokenizer",
    "load_production_target_engine",
    "load_native_grammar_runtime",
    "load_torch_cuda_target",
    "probe_torch_cuda",
    "probe_quantized_target",
    "qualify_qwen_3b_candidate",
    "select_highest_logit",
    "select_cuda_argmax",
    "validate_selection_policy",
]
