[package]
name = "onyx_cuda_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "_rust"
crate-type = ["cdylib", "rlib"]

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = "0.22"
regex = "1"
regex-automata = { version = "0.4", features = ["dfa", "dfa-build", "dfa-search", "syntax"] }
serde_json = "1"
